// Port of generateMarkdownReport() from Automated-Quality-Gate/generate-tests.js.
// Produces the Markdown the GitHub Action posts as a PR comment, so the CI job
// summary shows the same artifact.
//
// PORT NOTE: plain-ESM copy of quality-gate-ui/src/lib/report.ts.
export function buildMarkdownReport(summary) {
  const ok = (s) => (s ? "✅" : "❌");
  const sonarEmoji = summary.sonar?.passed ? "✅" : "❌";

  const classificationTable = `
### 🤖 AI Code Classification & Status
| File | Importance | Target % | Actual % | Status |
| :--- | :--- | :--- | :--- | :--- |
${summary.modifiedFiles
  .map((f) => {
    const c = summary.classifications[f];
    const s = summary.fileStatus[f] || { actual: 0, required: 0, pass: false };
    const target = c?.targetCoverage || c?.min_coverage_threshold || 0;
    return `| \`${f}\` | **${(c?.importance || "medium").toUpperCase()}** | ${target}% | ${s.actual}% | ${ok(s.pass)} |`;
  })
  .join("\n")}
`;

  const aiReviewSection = `
### 🕵️ AI Proactive Code Review
${summary.modifiedFiles
  .map((f) => {
    const c = summary.classifications[f];
    if (!c || !c.review) return "";
    const dot = c.review.status === "buggy" ? "🔴" : c.review.status === "suspicious" ? "🟡" : "🟢";
    return `
#### 📄 File: \`${f}\`
- **Audit Status:** ${dot} **${c.review.status.toUpperCase()}**
- **Analysis:** ${c.review.findings}
${
  c.review.remediation
    ? `\n> **💡 Suggested Fix:**\n> \`\`\`javascript\n> ${c.review.remediation.split("\n").join("\n> ")}\n> \`\`\``
    : ""
}
`;
  })
  .join("\n---\n")}
`;

  const sonarAnalysisSection = summary.sonarAnalysis
    ? `
---
### 🔍 AI SonarCloud Remediation
${summary.sonarAnalysis}
`
    : "";

  return `
# 🚀 AI-Powered Quality Gate Report

### 📊 Overall Result: ${ok(summary.success)} ${summary.success ? "PASS" : "FAIL"}

---
${classificationTable}

---
${aiReviewSection}

---

### 🛡️ Security & Audit
- **NPM Audit:** ${ok(summary.audit.isSecure)} ${summary.audit.isSecure ? "SECURE" : "VULNERABLE"}
- **Vulnerabilities:** [Critical: ${summary.audit.critical}, High: ${summary.audit.high}, Moderate: ${summary.audit.moderate}, Low: ${summary.audit.low}]

---

### 📡 SonarCloud Status
- **Quality Gate:** ${sonarEmoji} ${summary.sonar?.passed ? "PASSED" : "FAILED"}
- **Metrics:** [Bugs: ${summary.sonar?.metrics?.bugs || 0}, Vulns: ${summary.sonar?.metrics?.vulnerabilities || 0}, Smells: ${summary.sonar?.metrics?.code_smells || 0}]

${sonarAnalysisSection}

---

### 🤖 Automation Details
- **Tests Generated:** ${summary.testsGenerated}
- **Modified Files:** ${summary.modifiedFiles.map((f) => `\`${f}\``).join(", ")}

${summary.analysis ? `\n--- \n### 🔍 AI Test Failure Analysis\n${summary.analysis}\n` : ""}

---
*Generated by Automated Quality Gate — GitHub Actions*
  `.trim();
}
